title: Jkunst
tagline: R, Data & Code

email: jbkunst@gmail.com
layout: post

permalink: /:categories/:title/

baseurl: ""
url: "jbkunst.github.io"

markdown: redcarpet
markdown_ext:  markdown,mkdown,mkdn,mkd,md
redcarpet:
  extensions: ["tables", "autolink", "strikethrough", "space_after_headers", "with_toc_data", "fenced_code_blocks"]
