title: Jkunst
tagline: R, Data & Code

author:
  name: Joshua Kunst
  email: jbkunst@gmail.com
  twitter: jbkunst
  github: jbkunst
  
include: ['_pages']
  
layout: post
permalink: /:categories/:title/

url: http://jkunst.com

markdown: kramdown
markdown_ext:  markdown,mkdown,mkdn,mkd,md

kramdown:
  auto_ids: true
  input: GFM
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false
